#!/bin/sh
# [Clauderizer] SessionStart wrapper — regenerated by `clauderize init`; do not edit.
# A session whose engine cannot launch must still learn why (H-01): any
# engine failure becomes a breadcrumb on STDOUT (the session context).
# engine-hook: /home/ccusce/Clauderizer/.venv/bin/clauderizer-hook
out=$(/home/ccusce/Clauderizer/.venv/bin/clauderizer-hook "$@" 2>&1)
status=$?
if [ "$status" -eq 0 ]; then
  [ -n "$out" ] && printf '%s\n' "$out"
else
  printf '[Clauderizer] engine unreachable: exit %s from %s — run `clauderize doctor`\n%s\n' \
    "$status" "/home/ccusce/Clauderizer/.venv/bin/clauderizer-hook" "$out"
fi
exit 0
