"""Assemble a cumulative, self-contained phase handoff.

The original procedure's #2 anti-pattern is "incomplete lesson propagation":
a phase repeats a mistake an earlier phase already solved because the lesson
wasn't carried forward. The fix was the "self-contained handoff" rule — every
handoff carries ALL still-relevant lessons. Here that's an operation, not a
discipline: we read the single canonical lessons list and roll it up, pruning
only items explicitly marked obsolete/struck-through.
"""

from __future__ import annotations

import re
from pathlib import Path

from ..config import Config
from ..markdown import sections
from ..paths import RepoPaths

_LESSON_LINE = re.compile(r"^\s*\*\*\d+\.\*\*")


def _gameplan_text(paths: RepoPaths, gid: str, name: str) -> str:
    p = paths.gameplan_dir(gid) / name
    return p.read_text(encoding="utf-8") if p.exists() else ""


def collect_lessons(index_text: str) -> tuple[str, int]:
    """Return ``(rolled_up_markdown, count)`` of still-relevant lessons.

    Preserves the category sub-headings; drops any lesson line marked
    ``(obsolete)`` or wrapped in ``~~strikethrough~~``.
    """
    sec = sections.get_section(index_text, "Accumulated Lessons")
    if not sec:
        return "_(no lessons recorded yet)_", 0
    out_lines: list[str] = []
    count = 0
    for line in sec.splitlines():
        stripped = line.strip()
        if _LESSON_LINE.match(stripped):
            if "(obsolete)" in stripped.lower() or stripped.startswith("~~"):
                continue
            count += 1
            out_lines.append(line)
        else:
            out_lines.append(line)
    # collapse blank runs
    rolled = re.sub(r"\n{3,}", "\n\n", "\n".join(out_lines)).strip()
    return rolled, count


def _phase_section(gameplan_text: str, phase_n: str) -> str | None:
    return sections.get_section(gameplan_text, f"Phase {phase_n}") or None


def assemble(paths: RepoPaths, config: Config, gid: str, phase_n: str) -> dict:
    index_text = _gameplan_text(paths, gid, "CHAT-HANDOFF-INDEX.md")
    gameplan_text = _gameplan_text(paths, gid, "GAMEPLAN.md")
    lessons_md, lessons_count = collect_lessons(index_text)
    phase_body = _phase_section(gameplan_text, phase_n)

    parts = [
        f"# Phase {phase_n} Handoff",
        "",
        "> For: next Clauderizer session",
        f"> Gameplan: {gid}",
        f"> Generated by: cz_write_handoff",
        "",
        "## What This Phase Does",
        "",
        (phase_body.strip() if phase_body else "_(see GAMEPLAN.md for the phase definition)_"),
        "",
        "## Pre-Flight Verification (MANDATORY)",
        "",
        "Run `cz_preflight` before touching code. All enabled checks must pass.",
        "",
        "## Key Files You Must Read",
        "",
        f"- `docs/gameplans/{gid}/GAMEPLAN.md`",
        f"- `docs/gameplans/{gid}/PHASE-STATUS.md`",
        "- `CLAUDE.md`",
        "",
        "## Accumulated Lessons (Cumulative — All Prior Phases)",
        "",
        lessons_md,
        "",
        "## Ending Protocol",
        "",
        "1. Update PHASE-STATUS.md (status + outputs + corrections).",
        "2. `cz_add_lesson` for anything new.",
        "3. `cz_transition_status` on touched entities (fires cascade).",
        "4. `cz_write_handoff` for the next phase.",
        "5. Run exit verification; report the test count.",
        "",
    ]
    text = "\n".join(parts)
    out_path = paths.gameplan_dir(gid) / "handoffs" / f"PHASE-{phase_n}-HANDOFF.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    return {
        "ok": True,
        "path": str(out_path),
        "lessons_rolled_up": lessons_count,
        "summary": f"wrote handoff for phase {phase_n}: {lessons_count} lessons rolled up",
    }
