"""Assemble a cumulative, self-contained phase handoff.

The original procedure's #2 anti-pattern is "incomplete lesson propagation":
a phase repeats a mistake an earlier phase already solved because the lesson
wasn't carried forward. The fix was the "self-contained handoff" rule — every
handoff carries ALL still-relevant lessons. Here that's an operation, not a
discipline: we read the single canonical lessons list and roll it up, pruning
only items explicitly marked obsolete/struck-through.
"""

from __future__ import annotations

import re
from pathlib import Path

from ..config import Config
from ..markdown import sections
from ..paths import RepoPaths

_LESSON_LINE = re.compile(r"^\s*\*\*\d+\.\*\*")
_PROJECT_LESSON_LINE = re.compile(r"^\s*\*\*L-\d+\.\*\*")


def _gameplan_text(paths: RepoPaths, gid: str, name: str) -> str:
    p = paths.gameplan_dir(gid) / name
    return p.read_text(encoding="utf-8") if p.exists() else ""


def collect_lessons(index_text: str) -> tuple[str, int]:
    """Return ``(rolled_up_markdown, count)`` of still-relevant lessons.

    Preserves the category sub-headings; drops any lesson line marked
    ``(obsolete …)`` (written by ``cz_obsolete_lesson``), ``(promoted …)``
    (written by ``cz_promote_lesson`` — the project section carries it from
    then on), or wrapped in ``~~strikethrough~~``.
    """
    return _filter_lessons(sections.get_section(index_text, "Accumulated Lessons"),
                           _LESSON_LINE)


def collect_project_lessons(lessons_text: str) -> tuple[str, int]:
    """Roll up the active ``L-NN`` entries of ``docs/LESSONS.md``."""
    return _filter_lessons(sections.get_section(lessons_text, "Lessons"),
                           _PROJECT_LESSON_LINE)


def _filter_lessons(sec: str | None, line_re: re.Pattern) -> tuple[str, int]:
    if not sec or not sec.strip():
        return "_(no lessons recorded yet)_", 0
    out_lines: list[str] = []
    count = 0
    for line in sec.splitlines():
        stripped = line.strip()
        if line_re.match(stripped):
            if ("(obsolete" in stripped.lower() or "(promoted" in stripped.lower()
                    or stripped.startswith("~~")):
                continue
            count += 1
            out_lines.append(line)
        else:
            out_lines.append(line)
    # collapse blank runs
    rolled = re.sub(r"\n{3,}", "\n\n", "\n".join(out_lines)).strip()
    return rolled, count


def _phase_section(gameplan_text: str, phase_n: str) -> str | None:
    return sections.get_section(gameplan_text, f"Phase {phase_n}") or None


# The engine owns only this marker-delimited region of a handoff file (D-008).
# Everything outside it — agent enrichment — is preserved byte-for-byte when
# the handoff is regenerated.
MARKER = "clauderizer:handoff"

# Pre-marker handoffs written by this generator carry this line; such files are
# engine skeletons and are safe to replace wholesale on migration.
_GENERATED_FINGERPRINT = "> Generated by: cz_write_handoff"

_AGENT_SCAFFOLD = """\

## Phase Notes (agent-owned)

_(Enrich here: what exists / what does not yet, key constraints, captured
source-of-truth values for this phase. Everything outside the marker block
above survives `cz_write_handoff` regeneration.)_
"""


def _merge(existing: str, core: str) -> tuple[str, str]:
    """Combine the engine ``core`` with what's already on disk.

    Returns ``(merged_text, mode)`` where mode describes what happened:
    ``created`` (fresh file, scaffold added), ``merged`` (marker block replaced,
    rest byte-preserved), ``migrated`` (legacy generated skeleton replaced), or
    ``preserved`` (unrecognized file kept verbatim below the block).
    """
    if existing and sections.has_marker_block(existing, MARKER):
        return sections.upsert_marker_block(existing, MARKER, core), "merged"
    block = sections.upsert_marker_block("", MARKER, core)
    if not existing:
        return block + _AGENT_SCAFFOLD, "created"
    if _GENERATED_FINGERPRINT in existing:
        return block + _AGENT_SCAFFOLD, "migrated"
    return block + "\n" + existing, "preserved"


def assemble(paths: RepoPaths, config: Config, gid: str, phase_n: str, *, write: bool = True) -> dict:
    index_text = _gameplan_text(paths, gid, "CHAT-HANDOFF-INDEX.md")
    gameplan_text = _gameplan_text(paths, gid, "GAMEPLAN.md")
    lessons_md, lessons_count = collect_lessons(index_text)
    phase_body = _phase_section(gameplan_text, phase_n)

    # Distilled project lessons (docs/LESSONS.md) ride along in every handoff,
    # across gameplans — that's what promotion buys (D-009).
    project_lessons_md, project_count = "", 0
    lessons_doc = paths.doc("LESSONS")
    if lessons_doc.exists():
        project_lessons_md, project_count = collect_project_lessons(
            lessons_doc.read_text(encoding="utf-8"))

    parts = [
        f"# Phase {phase_n} Handoff",
        "",
        "> For: next Clauderizer session",
        f"> Gameplan: {gid}",
        f"> Generated by: cz_write_handoff",
        "",
        "## What This Phase Does",
        "",
        (phase_body.strip() if phase_body else "_(see GAMEPLAN.md for the phase definition)_"),
        "",
        "## Pre-Flight Verification (MANDATORY)",
        "",
        "Run `cz_preflight` before touching code. All enabled checks must pass.",
        "",
        "## Key Files You Must Read",
        "",
        f"- `docs/gameplans/{gid}/GAMEPLAN.md`",
        f"- `docs/gameplans/{gid}/PHASE-STATUS.md`",
        "- `CLAUDE.md`",
        "",
        "## Accumulated Lessons (Cumulative — All Prior Phases)",
        "",
        lessons_md,
        "",
    ]
    if project_count:
        parts += [
            "## Project Lessons (distilled — survive across gameplans)",
            "",
            project_lessons_md,
            "",
        ]
    parts += [
        "## Ending Protocol",
        "",
        "1. Update PHASE-STATUS.md (status + outputs + corrections).",
        "2. `cz_add_lesson` for anything new.",
        "3. `cz_transition_status` on touched entities (fires cascade).",
        "4. `cz_write_handoff` for the next phase.",
        "5. Run exit verification; report the test count.",
        "",
    ]
    core = "\n".join(parts)
    out_path = paths.gameplan_dir(gid) / "handoffs" / f"PHASE-{phase_n}-HANDOFF.md"
    existing = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
    # The merged view is computed even for write=False so a context fetch
    # (cz_next_phase_context) includes any agent enrichment already on disk.
    text, mode = _merge(existing, core)
    if write:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text, encoding="utf-8")
        summary = (f"wrote handoff for phase {phase_n} ({mode}): "
                   f"{lessons_count} lessons rolled up")
    else:
        summary = f"assembled phase {phase_n} context: {lessons_count} lessons rolled up (not written)"
    return {
        "ok": True,
        "path": str(out_path) if write else None,
        "written": write,
        "mode": mode,
        "handoff_md": text,
        "lessons_rolled_up": lessons_count,
        "project_lessons": project_count,
        "summary": summary,
    }
