from pathlib import Path

from clauderizer import config as cfg
from clauderizer import paths as P
from clauderizer.profiles.detect import Profile
from clauderizer.rituals import handoff, preflight, status_bundle


def _paths_and_config(repo: Path):
    paths = P.resolve(repo)
    config = cfg.Config.load(paths.config_file)
    return paths, config


def test_status_bundle_identifies_current_phase(sample_repo):
    paths, config = _paths_and_config(sample_repo)
    bundle = status_bundle.compute(paths, config)
    assert bundle["active_gameplan"] == "2026-05-01-bootstrap"
    assert bundle["current_phase"]["number"] == "1"
    assert bundle["current_phase"]["name"] == "Wire it up"
    assert len(bundle["phases"]) == 2
    assert bundle["pending_cascades"] == []
    assert "IN PROGRESS" in bundle["summary"]


def test_status_digest_render(sample_repo):
    paths, config = _paths_and_config(sample_repo)
    bundle = status_bundle.compute(paths, config)
    digest = status_bundle.render_digest(bundle, tools=["cz_status", "cz_preflight"])
    assert digest.startswith("[Clauderizer]")
    assert "cz_status" in digest


def test_handoff_rolls_up_lessons(temp_repo):
    paths, config = _paths_and_config(temp_repo)
    result = handoff.assemble(paths, config, "2026-05-01-bootstrap", "1")
    out = Path(result["path"])
    assert out.exists()
    text = out.read_text(encoding="utf-8")
    # All three non-obsolete lessons carried forward.
    assert result["lessons_rolled_up"] == 3
    assert "Markdown is canonical" in text
    assert "Cascade is post-hoc" in text


def test_handoff_prunes_obsolete_lessons(temp_repo):
    # Add an obsolete lesson and confirm it's dropped.
    paths, config = _paths_and_config(temp_repo)
    idx = paths.gameplan_dir("2026-05-01-bootstrap") / "CHAT-HANDOFF-INDEX.md"
    text = idx.read_text(encoding="utf-8")
    # D8: the obsolescence marker is line-final (the only form the blessed
    # write produces); a leading "(obsolete)" with text after it is just text.
    text = text.replace(
        "**3.** Keep fixtures small and hand-verifiable.",
        "**3.** Keep fixtures small and hand-verifiable.\n\n**4.** old advice. (obsolete 2026-06-01)",
    )
    idx.write_text(text, encoding="utf-8")
    result = handoff.assemble(paths, config, "2026-05-01-bootstrap", "2")
    assert result["lessons_rolled_up"] == 3  # obsolete one pruned
    assert "old advice" not in Path(result["path"]).read_text(encoding="utf-8")


def test_handoff_first_write_has_markers_and_agent_scaffold(temp_repo):
    paths, config = _paths_and_config(temp_repo)
    result = handoff.assemble(paths, config, "2026-05-01-bootstrap", "2")
    assert result["mode"] == "created"
    text = Path(result["path"]).read_text(encoding="utf-8")
    assert "<!-- clauderizer:handoff:start -->" in text
    assert "<!-- clauderizer:handoff:end -->" in text
    assert "## Phase Notes (agent-owned)" in text


def test_handoff_regeneration_preserves_enrichment(temp_repo):
    from clauderizer import mutations as M

    paths, config = _paths_and_config(temp_repo)
    gid = "2026-05-01-bootstrap"
    first = handoff.assemble(paths, config, gid, "2")
    out = Path(first["path"])

    # Agent enriches outside the marker block
    enrichment = (
        "\n## Phase Notes (agent-owned)\n\n"
        "Key constraint: never touch the legacy auth table.\n"
        "Captured: STRIPE_CUSTOMER_PREFIX=cus_test_\n"
    )
    text = out.read_text(encoding="utf-8")
    end = "<!-- clauderizer:handoff:end -->"
    before_block, after_block = text.split(end, 1)
    out.write_text(before_block + end + enrichment, encoding="utf-8")

    # New lesson lands, handoff regenerated
    M.add_lesson(paths, gameplan_id=gid, text="always capture env prefixes", category="Process")
    second = handoff.assemble(paths, config, gid, "2")
    assert second["mode"] == "merged"
    new_text = out.read_text(encoding="utf-8")
    # enrichment outside the block survives byte-for-byte
    assert new_text.endswith(enrichment)
    # the engine block was refreshed
    assert "always capture env prefixes" in new_text.split(end, 1)[0]


def test_handoff_migrates_legacy_generated_skeleton(temp_repo):
    paths, config = _paths_and_config(temp_repo)
    gid = "2026-05-01-bootstrap"
    out = paths.gameplan_dir(gid) / "handoffs" / "PHASE-2-HANDOFF.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "# Phase 2 Handoff\n\n> For: next Clauderizer session\n"
        "> Generated by: cz_write_handoff\n\n## What This Phase Does\n\nold skeleton\n",
        encoding="utf-8",
    )
    result = handoff.assemble(paths, config, gid, "2")
    assert result["mode"] == "migrated"
    text = out.read_text(encoding="utf-8")
    assert "<!-- clauderizer:handoff:start -->" in text
    assert "old skeleton" not in text  # legacy generated content fully replaced


def test_handoff_preserves_unrecognized_file_below_block(temp_repo):
    paths, config = _paths_and_config(temp_repo)
    gid = "2026-05-01-bootstrap"
    out = paths.gameplan_dir(gid) / "handoffs" / "PHASE-2-HANDOFF.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    hand_written = "# My hand-written phase 2 notes\n\nDo not lose this.\n"
    out.write_text(hand_written, encoding="utf-8")
    result = handoff.assemble(paths, config, gid, "2")
    assert result["mode"] == "preserved"
    text = out.read_text(encoding="utf-8")
    assert text.endswith(hand_written)
    assert "<!-- clauderizer:handoff:start -->" in text


def test_next_phase_context_merged_view_includes_enrichment(temp_repo):
    paths, config = _paths_and_config(temp_repo)
    gid = "2026-05-01-bootstrap"
    first = handoff.assemble(paths, config, gid, "2")
    out = Path(first["path"])
    out.write_text(out.read_text(encoding="utf-8") + "\nAgent breadcrumb.\n", encoding="utf-8")
    fetched = handoff.assemble(paths, config, gid, "2", write=False)
    assert fetched["written"] is False
    assert "Agent breadcrumb." in fetched["handoff_md"]
    # the fetch did not touch the file
    assert out.read_text(encoding="utf-8").endswith("Agent breadcrumb.\n")


def test_handoff_carries_promoted_lesson_exactly_once(temp_repo):
    from clauderizer import mutations as M

    paths, config = _paths_and_config(temp_repo)
    gid = "2026-05-01-bootstrap"
    M.promote_lesson(paths, gameplan_id=gid, number=3, today="2026-06-09")
    result = handoff.assemble(paths, config, gid, "2")
    assert result["project_lessons"] == 1
    assert result["lessons_rolled_up"] == 2  # promoted lesson left the gameplan roll-up
    text = Path(result["path"]).read_text(encoding="utf-8")
    assert "## Project Lessons (distilled — survive across gameplans)" in text
    assert text.count("Keep fixtures small and hand-verifiable.") == 1
    assert "**L-01.**" in text


def test_promoted_lessons_survive_into_a_new_gameplan(temp_repo):
    from clauderizer import mutations as M

    paths, config = _paths_and_config(temp_repo)
    M.promote_lesson(paths, gameplan_id="2026-05-01-bootstrap", number=3,
                     today="2026-06-09")
    M.create_gameplan(paths, "Next Initiative", today="2026-07-01")
    result = handoff.assemble(paths, config, "2026-07-01-next-initiative", "0")
    text = Path(result["path"]).read_text(encoding="utf-8")
    # the new gameplan has no lessons of its own, but inherits the distilled list
    assert result["lessons_rolled_up"] == 0
    assert result["project_lessons"] == 1
    assert "Keep fixtures small and hand-verifiable." in text


def test_handoff_omits_project_section_when_no_lessons_doc(temp_repo):
    paths, config = _paths_and_config(temp_repo)
    result = handoff.assemble(paths, config, "2026-05-01-bootstrap", "2")
    assert result["project_lessons"] == 0
    assert "Project Lessons" not in result["handoff_md"]


def _fake_runner(responses):
    def run(cmd, cwd):
        for key, val in responses.items():
            if key in cmd:
                return val
        return (0, "")
    return run


def test_preflight_passes_with_clean_tree_and_green_tests(sample_repo):
    paths, config = _paths_and_config(sample_repo)
    profile = Profile(
        name="python",
        commands={"test": "pytest -q"},
        baseline_test_regex=r"(\d+) passed",
    )
    runner = _fake_runner({
        "git status --porcelain": (0, ""),
        "pytest": (0, "5 passed in 0.1s"),
    })
    result = preflight.run(paths, config, profile, runner=runner)
    assert result.passed is True
    assert result.baseline_tests == "5"
    names = {c.name: c.status for c in result.checks}
    assert names["clean_tree"] == "pass"
    assert names["tests"] == "pass"


def test_preflight_fails_on_dirty_tree(sample_repo):
    paths, config = _paths_and_config(sample_repo)
    profile = Profile(name="python", commands={"test": "pytest -q"})
    runner = _fake_runner({
        "git status --porcelain": (0, " M somefile.py"),
        "pytest": (0, "5 passed"),
    })
    result = preflight.run(paths, config, profile, runner=runner)
    assert result.passed is False
    assert any(c.name == "clean_tree" and c.status == "fail" for c in result.checks)


def test_preflight_skips_when_no_test_command(sample_repo):
    paths, config = _paths_and_config(sample_repo)
    profile = Profile(name="generic", commands={})
    runner = _fake_runner({"git status --porcelain": (0, "")})
    result = preflight.run(paths, config, profile, runner=runner)
    assert any(c.name == "tests" and c.status == "skip" for c in result.checks)


def test_preflight_distinguishes_unborn_branch_from_no_repo(sample_repo):
    # A fresh `git init` with zero commits — the first thing a brand-new
    # adopter runs preflight on — must not read as "not a git repo"
    # (found live in the node-profile loop proof).
    paths, config = _paths_and_config(sample_repo)
    config.preflight_checks = ["branch_base", "clean_tree", "branch_creation"]
    profile = Profile(name="generic", commands={})
    runner = _fake_runner({
        "rev-parse --abbrev-ref HEAD": (128, "fatal: ambiguous argument 'HEAD'"),
        "rev-parse --is-inside-work-tree": (0, "true"),
        "git status --porcelain": (0, "?? scaffold"),
    })
    result = preflight.run(paths, config, profile, runner=runner)
    names = {c.name: (c.status, c.detail) for c in result.checks}
    assert names["branch_base"][0] == "skip"
    assert "no commits yet" in names["branch_base"][1]
    assert "not a git repo" not in names["branch_base"][1]
    assert names["branch_creation"][0] == "skip"
    assert "no commits yet" in names["branch_creation"][1]


def test_engine_staleness_detection():
    from clauderizer.rituals import status_bundle

    # files are always newer than the epoch; never newer than the future
    assert status_bundle.engine_source_newer_than(0.0) is True
    assert status_bundle.engine_source_newer_than(2_000_000_000.0) is False


def test_digest_nudges_on_stale_engine(sample_repo):
    from clauderizer.rituals import status_bundle

    paths, config = _paths_and_config(sample_repo)
    bundle = status_bundle.compute(paths, config)
    assert "Engine: source changed" not in status_bundle.render_digest(bundle)
    bundle["engine_stale"] = True
    out = status_bundle.render_digest(bundle)
    assert "⚠ Engine: source changed since this server started" in out
    assert "clauderize ops" in out  # the fresh-process escape hatch is named


def test_preflight_outside_any_repo_still_says_so(sample_repo):
    paths, config = _paths_and_config(sample_repo)
    config.preflight_checks = ["branch_base", "branch_creation"]
    profile = Profile(name="generic", commands={})
    runner = _fake_runner({
        "rev-parse --abbrev-ref HEAD": (128, "fatal: not a git repository"),
        "rev-parse --is-inside-work-tree": (128, "fatal: not a git repository"),
        "git status --porcelain": (128, "fatal: not a git repository"),
    })
    result = preflight.run(paths, config, profile, runner=runner)
    names = {c.name: c.detail for c in result.checks}
    assert names["branch_base"] == "not a git repo"
    assert names["branch_creation"] == "not a git repo"


def _add_baseline_line(paths, gid, count):
    idx = paths.gameplan_dir(gid) / "CHAT-HANDOFF-INDEX.md"
    idx.write_text(
        idx.read_text(encoding="utf-8")
        + f"\n## Pre-Flight Verification\n\n**Current baseline test count**: {count}\n",
        encoding="utf-8",
    )
    return idx


def test_preflight_writes_baseline_back(temp_repo):
    paths, config = _paths_and_config(temp_repo)
    idx = _add_baseline_line(paths, "2026-05-01-bootstrap", 5)
    profile = Profile(name="python", commands={"test": "pytest -q"},
                      baseline_test_regex=r"(\d+) passed")
    runner = _fake_runner({"git status --porcelain": (0, ""),
                           "pytest": (0, "7 passed in 0.1s")})
    result = preflight.run(paths, config, profile, runner=runner)
    assert result.baseline_tests == "7"
    assert "**Current baseline test count**: 7" in idx.read_text(encoding="utf-8")
    tests_check = next(c for c in result.checks if c.name == "tests")
    assert "baseline updated 5 -> 7" in tests_check.detail
    # idempotent: a second run finds the baseline already current
    result2 = preflight.run(paths, config, profile, runner=runner)
    tests_check2 = next(c for c in result2.checks if c.name == "tests")
    assert "baseline updated" not in tests_check2.detail


def test_preflight_no_write_back_on_failing_tests(temp_repo):
    paths, config = _paths_and_config(temp_repo)
    idx = _add_baseline_line(paths, "2026-05-01-bootstrap", 5)
    profile = Profile(name="python", commands={"test": "pytest -q"},
                      baseline_test_regex=r"(\d+) passed")
    runner = _fake_runner({"git status --porcelain": (0, ""),
                           "pytest": (1, "3 passed, 2 failed")})
    result = preflight.run(paths, config, profile, runner=runner)
    assert result.passed is False
    # a red run never rewrites the tracked baseline
    assert "**Current baseline test count**: 5" in idx.read_text(encoding="utf-8")


def test_preflight_write_back_tolerates_missing_baseline_line(temp_repo):
    paths, config = _paths_and_config(temp_repo)  # fixture index has no baseline line
    profile = Profile(name="python", commands={"test": "pytest -q"},
                      baseline_test_regex=r"(\d+) passed")
    runner = _fake_runner({"git status --porcelain": (0, ""),
                           "pytest": (0, "7 passed")})
    result = preflight.run(paths, config, profile, runner=runner)
    assert result.passed is True  # absence of the line is not an error


def test_memory_gauge_counts_states_and_sizes_handoff(temp_repo):
    from clauderizer import mutations as M

    paths, config = _paths_and_config(temp_repo)
    gid = "2026-05-01-bootstrap"
    M.promote_lesson(paths, gameplan_id=gid, number=3, today="2026-06-09")
    M.obsolete_lesson(paths, gameplan_id=gid, number=2, today="2026-06-09")
    bundle = status_bundle.compute(paths, config)
    mem = bundle["memory"]
    assert mem["active_lessons"] == 1
    assert mem["obsolete_lessons"] == 1
    assert mem["promoted_lessons"] == 1
    assert mem["project_lessons"] == 1
    assert mem["handoff_est_tokens"] > 0
    assert mem["warning"] is None
    digest = status_bundle.render_digest(bundle, tools=[])
    assert "Memory: 1 active lessons, 1 project" in digest
    assert "⚠ Memory" not in digest


def test_memory_gauge_warns_past_threshold(temp_repo):
    from clauderizer import mutations as M

    paths, config = _paths_and_config(temp_repo)
    gid = "2026-05-01-bootstrap"
    for i in range(status_bundle.ACTIVE_LESSONS_WARN):  # 3 fixture + 12 = 15 active
        M.add_lesson(paths, gameplan_id=gid, text=f"filler lesson {i}", category="Process")
    bundle = status_bundle.compute(paths, config)
    mem = bundle["memory"]
    assert mem["active_lessons"] == 15
    assert "cz_consolidate_lessons" in mem["warning"]
    digest = status_bundle.render_digest(bundle, tools=[])
    assert "⚠ Memory: 15 active lessons" in digest
    # consolidation is the way back under the line
    M.consolidate_lessons(paths, gameplan_id=gid,
                          numbers=list(range(4, 16)), text="all the filler, distilled")
    bundle = status_bundle.compute(paths, config)
    assert bundle["memory"]["active_lessons"] == 4
    assert bundle["memory"]["warning"] is None


def test_memory_thresholds_config_roundtrip(tmp_path):
    # O1/O2: the nudge lines are config, not constants — and survive the
    # to_toml <-> load round trip (L-04: engine-written files re-parse).
    from clauderizer.config import Config

    cfg = Config.for_size("standard")
    assert cfg.active_lessons_warn == 12  # the pre-O1 constant, honored
    assert cfg.project_lessons_warn == 20
    cfg.active_lessons_warn = 5
    cfg.project_lessons_warn = 7
    f = tmp_path / "config.toml"
    f.write_text(cfg.to_toml(), encoding="utf-8")
    loaded = Config.load(f)
    assert loaded.active_lessons_warn == 5
    assert loaded.project_lessons_warn == 7
    # configs that predate [memory] load with the defaults
    f.write_text("[clauderizer]\nversion = \"1\"\n", encoding="utf-8")
    legacy = Config.load(f)
    assert legacy.active_lessons_warn == 12
    assert legacy.project_lessons_warn == 20


def test_memory_gauge_honors_configured_thresholds(temp_repo):
    # fixture has 3 active lessons and (after one promotion) 1 project lesson
    from clauderizer import mutations as M

    paths, config = _paths_and_config(temp_repo)
    M.promote_lesson(paths, gameplan_id="2026-05-01-bootstrap", number=3,
                     today="2026-06-09")
    config.active_lessons_warn = 1   # 2 active > 1
    config.project_lessons_warn = 0  # 1 project > 0
    bundle = status_bundle.compute(paths, config)
    warning = bundle["memory"]["warning"]
    assert "(> 1)" in warning and "cz_consolidate_lessons" in warning
    assert "project lessons (> 0)" in warning and "L-entries" in warning
    assert " | " in warning  # both nudges coexist, one digest line each
    digest = status_bundle.render_digest(bundle, tools=[])
    assert "⚠ Memory:" in digest
    # raise the lines back above the counts: silent again
    config.active_lessons_warn = 12
    config.project_lessons_warn = 20
    assert status_bundle.compute(paths, config)["memory"]["warning"] is None


def test_status_bundle_reports_completed_gameplan(temp_repo):
    from clauderizer import mutations as M

    paths, config = _paths_and_config(temp_repo)
    M.transition_phase(paths, gameplan_id="2026-05-01-bootstrap", phase_n="1",
                       to_status="complete", today="2026-06-09")
    bundle = status_bundle.compute(paths, config)
    assert "all 2 phase(s) COMPLETE" in bundle["summary"]
    assert "no in-progress or ready phase" not in bundle["summary"]
    assert "Close out the gameplan" in bundle["next_action"]
